package com.specskart.whatsapp;

public enum BotIntent {
    FIND_FRAMES, EXPLORE_FRAMES, VISIT_WEBSITE,
    RESULTS_SHOW_FRAMES, RESULTS_NOT_NOW,
    HELP_CHOOSE, BUDGET_LOW, BUDGET_MED, BUDGET_HIGH,
    GREETING, UNKNOWN
}
