package com.specskart.analytics;

public enum LeadEventType {
    AD_LANDING,
    WHATSAPP_CONVERSATION_STARTED,
    WHATSAPP_MESSAGE_RECEIVED,
    WHATSAPP_AUTOREPLY_SENT,
    FRAME_FINDER_LINK_SENT,
    FRAME_FINDER_OPENED,
    CAMERA_PERMISSION_GRANTED,
    CAMERA_PERMISSION_DENIED,
    PHOTO_CAPTURED,
    FACE_ANALYSIS_STARTED,
    FACE_ANALYSIS_COMPLETED,
    FACE_ANALYSIS_FAILED,
    RECOMMENDATION_VIEWED,
    WHATSAPP_RESULTS_REQUESTED,
    EXPERT_CONTACT_REQUESTED, // retired flow — kept so historical lead_events rows still deserialize
    WHATSAPP_FOLLOW_UP_SENT,
    WHATSAPP_NURTURE_SENT,
    WHATSAPP_NURTURE_ENDED,
    PRODUCTS_SHOWN,
    ORDER_PLACED,
    ORDER_PAID,
    ORDER_DELIVERED,
    REVIEW_REQUESTED,
    LEAD_CONVERTED
}
